/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordermanagement;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import ordermanagement.dbconnect.Dbconnect;

/**
 *
 * @author Shani
 */
public class customerregistation extends javax.swing.JFrame {

       
    Connection con =  null;  
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    /**
     * Creates new form dilivaryManagement
     */
    public customerregistation() {
        initComponents();
       con= Dbconnect.connect();
        
         {
            Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
         
          // set auto date and time on top of the page 
       
       Date.setFont(new Font("Iskoola Pota",1,18));
       Time.setFont(new Font("Iskoola Pota",1,18));
          ShowTime();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtName1 = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        custid1 = new javax.swing.JTextField();
        txtcard = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Date);
        Date.setBounds(1100, 150, 220, 40);

        Time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Time);
        Time.setBounds(1100, 100, 210, 40);

        jButton21.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jButton21.setText("Home");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(1110, 30, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cvbnmsdfghjk.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -50, 1430, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1410, 210);

        jPanel2.setLayout(null);

        txtName1.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        txtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtName1KeyPressed(evt);
            }
        });
        jPanel2.add(txtName1);
        txtName1.setBounds(290, 90, 280, 30);

        txtaddress.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaddressKeyPressed(evt);
            }
        });
        jPanel2.add(txtaddress);
        txtaddress.setBounds(290, 170, 280, 30);

        txtnic.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        jPanel2.add(txtnic);
        txtnic.setBounds(290, 130, 280, 30);

        txttel.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
        });
        jPanel2.add(txttel);
        txttel.setBounds(290, 210, 280, 30);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 170, 120, 30);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 330, 120, 30);

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone No");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 210, 130, 30);

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registerd customers  ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(920, 130, 240, 40);

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 130, 110, 30);

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login to the site");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(950, 180, 200, 40);

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton3.setText("Click hear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(860, 380, 230, 40);

        jButton6.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton6.setText("Register");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(130, 460, 140, 40);

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton2.setText("Cancel ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(340, 460, 140, 40);

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New Customer Registation");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(110, 10, 350, 40);

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Register to site");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(150, 40, 200, 40);

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 250, 100, 30);

        txtemail.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        jPanel2.add(txtemail);
        txtemail.setBounds(290, 250, 280, 30);

        custid1.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        custid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custid1KeyPressed(evt);
            }
        });
        jPanel2.add(custid1);
        custid1.setBounds(940, 250, 310, 30);

        txtcard.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        txtcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcardKeyPressed(evt);
            }
        });
        jPanel2.add(txtcard);
        txtcard.setBounds(290, 290, 280, 30);

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("User name (Email)");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(740, 250, 170, 30);

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 90, 120, 30);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(940, 310, 310, 30);
        jPanel2.add(txtPassword);
        txtPassword.setBounds(290, 330, 280, 30);

        jLabel17.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(740, 310, 120, 30);

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Card number");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(80, 290, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos-abstractos-corel-draw-para-fondo-celular-en-hd-12.jpg"))); // NOI18N
        jLabel8.setText("                                                                                            ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-30, 0, 1810, 580);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 210, 1400, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void ShowTime(){

      Thread t=new Thread(){
      public void run(){
           for(;;){
              Calendar calenda=new GregorianCalendar();
              int day=calenda.get(calenda.DAY_OF_MONTH);
              int month=calenda.get(calenda.MONTH);
              int year=calenda.get(calenda.YEAR);
              Date.setText("Date :"+day+"/"+(month+1)+"/"+year);
              
             
              int hour=calenda.get(calenda.HOUR);
              int minute=calenda.get(calenda.MINUTE);
              int Second=calenda.get(calenda.SECOND);
              
              Time.setText("Time :" +hour+ ":" +minute+ ":" +Second);
              try{
                 sleep(1000);
                 
              }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
              }
           }
      };
             
      t.start();
      
}
     
     
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // click hear button
        
        try{  
            String query = "SELECT email,password FROM customer";
            pst = con.prepareStatement(query);
            rs  = pst.executeQuery();
        
        
        
        }
        catch(Exception e){
        
        
        }
        
       
        dilivaryinfo di= new  dilivaryinfo();
        di.setVisible(true);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // cancel button
        
       
      
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // register button
        
           try {
                int x=JOptionPane.showConfirmDialog(null, "Do you want to save this record");
         
                 if(x==0){
                     
                    
            /*      
                 String q= "INSERT INTO customer(name,nic,address,tel,email,credictcard,password) VALUES ('"+txtName1.getText()+"','"+txtnic.getText()+"','"+ txtaddress.getText()+"','"+txttel.getText()+"','"+txtemail.getText()+"','"+txtcard.getText()+"','"+txtPassword.getText()+"')";
                 pst =conn.prepareStatement(q);
                 pst.execute();
            
                 txtName1.setText("");
                 txtnic.setText("");
                 txtaddress.setText("");
                 txttel.setText(""); 
                 txtemail.setText(""); 
                 txtcard.setText("");
                 txtPassword.setText("");
                 
                     */
            
            String s= "INSERT INTO customer(name,nic,address,tel,email,credictcard,password) VALUES('"+txtName1.getText()+"','"+txtnic.getText()+"','"+ txtaddress.getText()+"','"+txttel.getText()+"','"+txtemail.getText()+"','"+txtcard.getText()+"','"+txtPassword.getText()+"')";
            //System.out.println(jLabel24.getText());
            pst =con.prepareStatement(s);
            pst.execute();
                 
                     
        }
        else if(x==1){
        }
        
    } catch (Exception e) {
               System.out.println(e);
    } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // homebutton

        home h= new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelKeyPressed

    private void txtaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyPressed

    private void custid1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custid1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_custid1KeyPressed

    private void txtcardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcardKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcardKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerregistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField custid1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcard;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
