/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordermanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ordermanagement.dbconnect.Dbconnect;
import java.util.*;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shani
 */
public class ItemManagement extends javax.swing.JFrame {

     
      Connection con =  Dbconnect.connect();  
      PreparedStatement pst =null;
      ResultSet rs = null;
    
    /**
     * Creates new form ItemManagement
     */
    public ItemManagement() {
        initComponents();
        id();
        tableload2();
         {
            Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
       // set auto date and time on top of the page 
       
       Date.setFont(new Font("Iskoola Pota",1,18));
       Time.setFont(new Font("Iskoola Pota",1,18));
          ShowTime();  
    }
    
    public  void id(){
         
            int sum = 0;
         try {
             String query = "SELECT * FROM expenditures ORDER BY Exp_ID DESC LIMIT 1";
            pst = con.prepareStatement(query);
            rs  = pst.executeQuery();
            
            while(rs.next()){
                int s = Integer.parseInt(rs.getString("Exp_ID"));
                 sum = s + 1;
               // txtfno.setText(String.valueOf(sum));
            }
        } catch (Exception e) {
        }
     }
    
    
    public void ShowTime(){

      Thread t=new Thread(){
      public void run(){
           for(;;){
              Calendar calenda=new GregorianCalendar();
              int day=calenda.get(calenda.DAY_OF_MONTH);
              int month=calenda.get(calenda.MONTH);
              int year=calenda.get(calenda.YEAR);
              Date.setText("Date :"+day+"/"+(month+1)+"/"+year);
              
             
              int hour=calenda.get(calenda.HOUR);
              int minute=calenda.get(calenda.MINUTE);
              int Second=calenda.get(calenda.SECOND);
              
              Time.setText("Time :" +hour+ ":" +minute+ ":" +Second);
              try{
                 sleep(1000);
                 
              }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
              }
           }
      };
             
      t.start();
      
}
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        Time = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareadisc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblitems = new javax.swing.JTable();
        cmboxcategory = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Date);
        Date.setBounds(1100, 180, 220, 40);

        jButton21.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jButton21.setText("Home");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(1170, 30, 130, 40);

        Time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Time);
        Time.setBounds(1100, 130, 210, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cvbnmsdfghjk.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1420, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1420, 240);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 50, 100, 30);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 110, 120, 30);
        jPanel2.add(lblImage);
        lblImage.setBounds(510, 70, 140, 140);

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 170, 110, 30);

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Discription");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 300, 100, 30);

        txtName.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtName);
        txtName.setBounds(180, 110, 240, 30);

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });
        jPanel2.add(txtprice);
        txtprice.setBounds(180, 230, 240, 30);

        txtareadisc.setColumns(20);
        txtareadisc.setRows(5);
        jScrollPane1.setViewportView(txtareadisc);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(180, 290, 240, 100);

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton1.setText("Upload Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(510, 270, 160, 40);

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton2.setText("Cancel ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(180, 410, 140, 40);

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton3.setText("Add details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 410, 140, 40);

        jButton5.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton5.setText("Delete item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(500, 410, 140, 40);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);

        tblitems.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        tblitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "category", "price", "discriception"
            }
        ));
        tblitems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblitemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblitems);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 590, 270);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(750, 130, 590, 270);

        cmboxcategory.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        cmboxcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category", "Normal shoes", "Shoe for bride", "Party shoes", "High heels", "coat shoes", "kids shoes", " " }));
        jPanel2.add(cmboxcategory);
        cmboxcategory.setBounds(180, 170, 240, 30);

        jButton4.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton4.setText("Update item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(340, 410, 140, 40);

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(60, 230, 100, 30);

        lblId.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblId);
        lblId.setBounds(180, 50, 230, 30);
        jPanel2.add(jFileChooser1);
        jFileChooser1.setBounds(530, 290, 20, 10);

        jButton6.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton6.setText("All Items Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(680, 410, 180, 40);

        jButton7.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton7.setText("All Registered Customers");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(920, 410, 270, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos-abstractos-corel-draw-para-fondo-celular-en-hd-12.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-320, -40, 1810, 590);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 240, 1380, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //  Upload image button
        
        
         try {
        jFileChooser1.showOpenDialog(this);
        File f=jFileChooser1.getSelectedFile();
        String path=f.getAbsolutePath();
        path=path.replace("\\","/");
        File f1=new File(path);
        
        Image im=ImageIO.read(f1);
        im=im.getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);
       lblImage.setIcon(new ImageIcon(im));
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Save button
        
         try {
         File f=jFileChooser1.getSelectedFile();
         String path=f.getAbsolutePath();
         path=path.replace("\\","/");
         
        int x=JOptionPane.showConfirmDialog(null, "Do you want to save this record");
         
        if(x==0){
            Connection c =Dbconnect.connect();
            Statement s = c.createStatement();
            s.executeUpdate("INSERT INTO items_shoe (name,category,price,Discription,image) VALUES ('"+txtName.getText()+"','"+cmboxcategory.getSelectedItem()+"','"+txtprice.getText()+"','"+txtareadisc.getText()+"','"+path+"')");
                 
                 txtName.setText("");
                 cmboxcategory.setSelectedItem("");
                 txtprice.setText("");
                 txtareadisc.setText(""); 
                 lblImage.setText("");
            
        }
        else if(x==1){
        }
        
    } catch (Exception e) {
        e.printStackTrace();
        
        
        
    }       
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void tableload2(){
    // table load to check availabity
        try{
       //     SimpleDateFormat txbxdate=jDateChooser1.getDate();
       
            
            String sqlavailabl="SELECT *from items_shoe";
              pst = con.prepareStatement(sqlavailabl);
              rs= pst.executeQuery(sqlavailabl);
              tblitems.setModel(DbUtils.resultSetToTableModel(rs));
              

            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // update button
        
         String path = null;
  try {
       int x=JOptionPane.showConfirmDialog(rootPane, "Do you want to update this record");
       if (x==0){
        Connection c=Dbconnect.connect();
        Statement s=c.createStatement();
        s.executeUpdate( "UPDATE items_shoe SET price '"+txtprice.getText()+"' WHERE itemid'"+lblId.getText()+"'");
        JOptionPane.showMessageDialog(rootPane, "successfully update!!"); 
       
       }
       else if(x==1){
                 lblId.setText("--");
                 txtName.setText("");
                 cmboxcategory.setSelectedItem("");
                 txtprice.setText("");
                 txtareadisc.setText(""); 
                 lblImage.setText("");  
       }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // cancel button 
                   lblId.setText("--");
                 txtName.setText("");
                 cmboxcategory.setSelectedItem("");
                 txtprice.setText("");
                 txtareadisc.setText(""); 
                 lblImage.setText("");  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Delete button
        try {
        
        Connection c=Dbconnect.connect();
        Statement s=c.createStatement();
        s.executeUpdate("DELETE FROM items_shoe WHERE itemid'"+lblId.getText()+"'");
        
                lblId.setText("--");
                 txtName.setText("");
                 cmboxcategory.setSelectedItem("");
                 txtprice.setText("");
                 txtareadisc.setText(""); 
                 lblImage.setText("");  
        
       
        
    } catch (Exception e) {
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
          // search customer

        String search = txtName.getText();
        String sql =" SELECT * FROM items_shoe where name LIKE '%"+ search +"%' ORDER BY `name`.`CustID` ASC ";

        try{
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            tblitems.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e){

        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // homebutton

        home h= new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void tblitemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblitemsMouseClicked
        //mouse click and select raw
          int row = tblitems.getSelectedRow();
          
           String id = tblitems.getValueAt(row, 0).toString();
           String name = tblitems.getValueAt(row, 1).toString();
           String category = tblitems.getValueAt(row, 2).toString();
           String price = tblitems.getValueAt(row, 3).toString();
           String disc= tblitems.getValueAt(row, 4).toString();
           String image= tblitems.getValueAt(row, 5).toString();
           
          
         lblId.setText(id);
         txtName.setText(name);
         cmboxcategory.setSelectedItem(category);
         txtprice.setText(price);
         txtareadisc.setText(disc);
         lblImage.setText(image);
    }//GEN-LAST:event_tblitemsMouseClicked

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
        // price 
        
                
               
         try{
            char c=evt.getKeyChar(); 
            
                if(Character.isLetter(c)&&!evt.isAltDown()){
                    
                  evt.consume();
                 Toolkit.getDefaultToolkit().beep();
            }                                                          
                
        }catch(Exception e){
  
        }
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // 
          String search = txtName.getText();
        
        String sql = "Select itemid,name,category,price,Discription from  items_shoe where name LIKE '%"+ search +"%' ORDER BY ` items_shoe`.`itemid` ASC";
        
        try {
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                tblitems.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
            catch(Exception e){
                
            }
         
      
    }//GEN-LAST:event_txtNameKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            ReportViwer r= new ReportViwer("C:\\Users\\Shani\\Documents\\NetBeansProjects\\orderManagement\\reports\\items.jasper");
            r.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportViwer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportViwer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ReportViwer r= new ReportViwer("C:\\Users\\Shani\\Documents\\NetBeansProjects\\orderManagement\\reports\\users.jasper");
            r.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportViwer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportViwer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Time;
    private javax.swing.JComboBox<String> cmboxcategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblitems;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtareadisc;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
