/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordermanagement;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import ordermanagement.dbconnect.Dbconnect;

/**
 *
 * @author Shani
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        {
        Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
              lblEERROR.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblEERROR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cvbnmsdfghjk.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1450, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1460, 280);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 100, 120, 50);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 180, 110, 30);

        username.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(260, 110, 250, 30);

        jPasswordField1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(260, 170, 250, 30);

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(90, 280, 150, 30);

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(490, 280, 160, 30);

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(290, 280, 160, 30);

        lblEERROR.setText("jLabel4");
        jPanel2.add(lblEERROR);
        lblEERROR.setBounds(590, 110, 240, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos-abstractos-corel-draw-para-fondo-celular-en-hd-12.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(-440, 0, 1900, 490);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 280, 1450, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //login button
        String password = jPasswordField1.getText();
        String Username= username.getText();
        
        
        
       
        if(password.contains("ticktock")&&(Username.contains("ticktock")))
        {
            jPasswordField1.setText(null);
             username.setText(null);
             
             systemExit();
             ItemManagement info= new ItemManagement();
             info.setVisible(true);
       }
        else{
            JOptionPane.showMessageDialog(null,"Invalid loing details", "Loging Error",JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText(null);
             username.setText(null);
        
        }
        
          /*
        try {
        Connection c =Dbconnect.connect();
            java.sql.Statement s = c.createStatement();
        ResultSet rs=s.executeQuery("SELECT * FROM login");
        
        while(rs.next()){
        if(username.getText().equals(rs.getString("username"))&& jPasswordField1.getText().equals(rs.getString("password"))){
        
            System.out.println("dafdafad");
        break;
        }
        else{
           // JOptionPane.showMessageDialog(rootPane, "Invalide username and password!!!!");
            lblEERROR.setText("Invalide username and password!!!!");
            lblEERROR.setVisible(true);
        }
       
        }
        // new Home(txtusername.getText()).setVisible(true);
         this.dispose();
         
         
         
    } catch (Exception e) {
        e.printStackTrace();
    }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // clearbuttn
        
        username.setText("");
        jPasswordField1.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //exit buton
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblEERROR;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

private void systemExit(){

    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);

}


}
