/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordermanagement;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ordermanagement.dbconnect.Dbconnect;

/**
 *
 * @author Shani
 */
public class ShopingCart extends javax.swing.JFrame {

    /**
     * Creates new form ShopingCart
     */
    
    
    Connection con =  null;  
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    public ShopingCart(){
        
        
        initComponents();
        
        con= Dbconnect.connect();
         {
            Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
       // set auto date and time on top of the page 
       
       Date.setFont(new Font("Iskoola Pota",1,18));
       Time.setFont(new Font("Iskoola Pota",1,18));
          ShowTime();  
          id();
    }
    public  void id(){
         
            int sum = 0;
         try {
             String query = "SELECT * FROM  shoes ORDER BY no DESC LIMIT 1";
            pst = con.prepareStatement(query);
            rs  = pst.executeQuery();
            
            while(rs.next()){
                int s = Integer.parseInt(rs.getString("no"));
                 sum = s + 1;
                txtid.setText(String.valueOf(sum));
            }
        } catch (Exception e) {
        }
     }
    
    public void ShowTime(){

      Thread t=new Thread(){
      public void run(){
           for(;;){
              Calendar calenda=new GregorianCalendar();
              int day=calenda.get(calenda.DAY_OF_MONTH);
              int month=calenda.get(calenda.MONTH);
              int year=calenda.get(calenda.YEAR);
              Date.setText("Date :"+day+"/"+(month+1)+"/"+year);
              
             
              int hour=calenda.get(calenda.HOUR);
              int minute=calenda.get(calenda.MINUTE);
              int Second=calenda.get(calenda.SECOND);
              
              Time.setText("Time :" +hour+ ":" +minute+ ":" +Second);
              try{
                 sleep(1000);
                 
              }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
              }
           }
      };
             
      t.start();
      
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        p3 = new javax.swing.JLabel();
        BS3 = new javax.swing.JLabel();
        BS8 = new javax.swing.JLabel();
        BS1 = new javax.swing.JLabel();
        P8 = new javax.swing.JLabel();
        BS7 = new javax.swing.JLabel();
        P7 = new javax.swing.JLabel();
        P6 = new javax.swing.JLabel();
        BS5 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        BS2 = new javax.swing.JLabel();
        BS6 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        BS4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        total2 = new javax.swing.JLabel();
        CALCTOTAL = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        lbltotal1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        combo2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jPanel2.setLayout(null);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/2016-New-Design-Winged-font-b-Women-b-font-font-b-Sandals-b-font-font-b.jpg"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(190, 20, 180, 180);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/2017-wedding-ceremony-shoes-14cm-high-heel.jpg"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(370, 20, 170, 180);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/3fbcdcdbc4e115b1df42f1ecbfa8daf1.jpg"))); // NOI18N
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);
        jButton17.setBounds(10, 20, 180, 180);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/edshbtftrj.jpg"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);
        jButton18.setBounds(190, 230, 180, 180);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/ascsdevrv.jpg"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20);
        jButton20.setBounds(550, 20, 180, 180);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/fiuuukhjnbn.jpg"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton22);
        jButton22.setBounds(380, 230, 180, 180);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/plain-white-background.jpg"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton23);
        jButton23.setBounds(560, 230, 180, 180);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/bfdqwfsegs.jpg"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton24);
        jButton24.setBounds(10, 230, 180, 180);

        p3.setText("18000.00");
        jPanel2.add(p3);
        p3.setBounds(400, 80, 46, 20);

        BS3.setText("BS3");
        jPanel2.add(BS3);
        BS3.setBounds(430, 90, 34, 14);

        BS8.setText("BS8");
        jPanel2.add(BS8);
        BS8.setBounds(630, 370, 34, 14);

        BS1.setText("BS1");
        jPanel2.add(BS1);
        BS1.setBounds(70, 140, 34, 14);

        P8.setText("10000.00");
        jPanel2.add(P8);
        P8.setBounds(640, 350, 34, 14);

        BS7.setText("BS7");
        jPanel2.add(BS7);
        BS7.setBounds(430, 350, 34, 14);

        P7.setText("20000.00");
        jPanel2.add(P7);
        P7.setBounds(430, 320, 34, 14);

        P6.setText("17000.00");
        jPanel2.add(P6);
        P6.setBounds(250, 340, 34, 14);

        BS5.setText("BS5");
        jPanel2.add(BS5);
        BS5.setBounds(60, 310, 34, 14);

        P2.setText("20000.00");
        jPanel2.add(P2);
        P2.setBounds(250, 130, 50, 20);

        BS2.setText("BS2");
        jPanel2.add(BS2);
        BS2.setBounds(250, 160, 18, 14);

        BS6.setText("BS6");
        jPanel2.add(BS6);
        BS6.setBounds(230, 350, 34, 14);

        P4.setText("23000.00");
        jPanel2.add(P4);
        P4.setBounds(620, 120, 34, 14);

        P1.setText("15000.00");
        jPanel2.add(P1);
        P1.setBounds(50, 130, 50, 14);

        P5.setText("16000.00");
        jPanel2.add(P5);
        P5.setBounds(90, 310, 34, 14);

        BS4.setText("BS4");
        jPanel2.add(BS4);
        BS4.setBounds(640, 140, 30, 14);

        jTabbedPane1.addTab("Bride's heels", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BRIDE/3fbcdcdbc4e115b1df42f1ecbfa8daf1.jpg"))); // NOI18N
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton25);
        jButton25.setBounds(10, 20, 180, 180);

        jTabbedPane1.addTab("Party high heels", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton1.setText("jButton1");
        jPanel3.add(jButton1);
        jButton1.setBounds(960, 165, 150, 120);

        jLabel21.setText("jLabel2");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(780, 265, 34, 14);

        jLabel22.setText("jLabel2");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(780, 285, 34, 14);

        jTabbedPane1.addTab("Party heels", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);
        jTabbedPane1.addTab("Coat shoes", jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);
        jTabbedPane1.addTab("Normal shoes", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);
        jTabbedPane1.addTab("Kid's wears", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 240, 750, 470);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        total2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        total2.setForeground(new java.awt.Color(255, 255, 255));
        total2.setText("Enter Shoe Size");
        jPanel9.add(total2);
        total2.setBounds(110, 70, 130, 40);

        CALCTOTAL.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        CALCTOTAL.setText("Calculate total");
        CALCTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCTOTALActionPerformed(evt);
            }
        });
        jPanel9.add(CALCTOTAL);
        CALCTOTAL.setBounds(120, 280, 160, 40);

        total.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("First add qty you want ");
        jPanel9.add(total);
        total.setBounds(110, 10, 230, 40);

        lbltotal1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        lbltotal1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(lbltotal1);
        lbltotal1.setBounds(250, 330, 170, 50);

        total1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));
        total1.setText("Total : Rs");
        jPanel9.add(total1);
        total1.setBounds(130, 330, 90, 50);

        jButton12.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton12.setText("Clear list");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton12);
        jButton12.setBounds(360, 280, 130, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Qty", "Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(80, 130, 450, 130);

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(50, 380, 160, 40);

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton3.setText("Delivery");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);
        jButton3.setBounds(440, 380, 150, 40);

        combo2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        jPanel9.add(combo2);
        combo2.setBounds(360, 10, 60, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enter Size", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel9.add(jComboBox1);
        jComboBox1.setBounds(360, 70, 130, 40);

        jButton4.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton4.setText("registor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);
        jButton4.setBounds(250, 380, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos-abstractos-corel-draw-para-fondo-celular-en-hd-12.jpg"))); // NOI18N
        jPanel9.add(jLabel1);
        jLabel1.setBounds(-1270, -130, 1950, 590);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(750, 270, 610, 440);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Date.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 204, 204));
        Date.setText("jLabel2");
        jPanel1.add(Date);
        Date.setBounds(1030, 210, 220, 40);

        jButton21.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jButton21.setText("Home");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(1040, 90, 130, 40);

        Time.setForeground(new java.awt.Color(255, 204, 204));
        Time.setText("jLabel2");
        jPanel1.add(Time);
        Time.setBounds(1030, 150, 230, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BILL NO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 80, 30);

        txtid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtid);
        txtid.setBounds(150, 10, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cvbnmsdfghjk.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1370, 270);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1410, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // homebutton
        
        home h= new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        //BS7
        String name = BS7.getText();
        String price=P7.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
        dtm.addRow(v);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        //  BS8
        String name = BS8.getText();
        String price=P8.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
        dtm.addRow(v);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void CALCTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCTOTALActionPerformed
        // CALC TOTAL
       
        
        
        
            DefaultTableModel dtm1 = (DefaultTableModel) jTable2.getModel();
        double sub =0;

        for(int n=0; n<dtm1.getRowCount();n++){
            sub += (double) dtm1.getValueAt(n, 3);
        }
       lbltotal1.setText(String.valueOf(sub));
    }//GEN-LAST:event_CALCTOTALActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //  CLEAR LIST
        DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel();
        dtm.removeRow(jTable2.getSelectedRow());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // bs6
        String name = BS6.getText();
        String price=P6.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        //       BS4
        String name = BS5.getText();
        String price=P5.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // bs4
        String name = BS4.getText();
        String price=P4.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // bs3
        String name = BS3.getText();
        String price=p3.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // bs2
        String name = BS2.getText();
        String price=P2.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
        
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        //bs1
        String name = BS1.getText();
        String price=P1.getText();
        String qty  = combo2.getSelectedItem().toString();

        double amt = Integer.parseInt(qty) * Double.parseDouble(price);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        Vector v = new Vector();

        v.add(name);
        v.add(price);
        v.add(qty);
        v.add(amt);
        
          dtm.addRow(v);
        

    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Save button
       
             int x = JOptionPane.showConfirmDialog(null, "do you  want to save this data?");
      if (x == 0) {
        
   try{
       for(int i=0; i< jTable2.getRowCount();i++){
            //String q= "INSERT INTO resturentmanagement(name) values('das')";
            String q= "INSERT INTO shoes(name,price,qty,amount,totalamount,size) values('"+jTable2.getValueAt(i, 0)+"','"+jTable2.getValueAt(i, 1)+"','"+jTable2.getValueAt(i, 2)+"','"+jTable2.getValueAt(i, 3)+"','"+lbltotal1.getText()+"','"+jComboBox1.getSelectedItem()+"')";
            //System.out.println(jLabel24.getText());
            pst =con.prepareStatement(q);
            pst.execute();
            
            

       }
          
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dilivaryinfo d= new dilivaryinfo();
        d.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        customerregistation c= new customerregistation();
        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopingCart().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BS1;
    private javax.swing.JLabel BS2;
    private javax.swing.JLabel BS3;
    private javax.swing.JLabel BS4;
    private javax.swing.JLabel BS5;
    private javax.swing.JLabel BS6;
    private javax.swing.JLabel BS7;
    private javax.swing.JLabel BS8;
    private javax.swing.JButton CALCTOTAL;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel P5;
    private javax.swing.JLabel P6;
    private javax.swing.JLabel P7;
    private javax.swing.JLabel P8;
    private javax.swing.JLabel Time;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbltotal1;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel txtid;
    // End of variables declaration//GEN-END:variables
}
